ARG XCUBE_VERSION="0.2.0.dev1"
FROM quay.io/bcdev/xcube:${XCUBE_VERSION}

# Person responsible
LABEL maintainer="helge.dzierzon@brockmann-consult.de"
LABEL name=xcube

LABEL version=${XCUBE_VERSION}

EXPOSE 4000

ENTRYPOINT ["bash","-c"]

CMD "source activate xcube && xcube serve -p 4000 -a 0.0.0.0"